/*
 * This source file was generated by the Gradle 'init' task
 */
package collection;

public class App {
    public String printHello() {
        return "Hello World";
    }
    public static void main(String[] args) {
    }
}
