/*
 * This source file was generated by the Gradle 'init' task
 */
package collection;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;

import static org.junit.jupiter.api.Assertions.*;


class AppTestList extends AbstractTestCollection<CarList> {

    @Override
    protected CarList createCollection() {
        return new CarArrayList();
    }

    @BeforeEach 
    void setUp() {
        collection = createCollection();
        for (int i = 0; i < 100; i++) {
            collection.add(new Car(i));
        }
    }

    @Test
    public void testGet() {
        for (int i = 0; i < 100; i++) {
            assertEquals(i, collection.get(i).getId());
        }
    }

    @Test
    public void whenElementAddedThenValueChanged() {
        Car car1 = new Car(30);
        collection.add(car1);
        assertEquals(30, collection.get(100).getId() );
        Car car2 = new Car(1000);
        collection.addAt(car2, 10);
        assertEquals(collection.get(10).getId(), 1000);
    }

    @Test
    public void whenElementRemovedThenValueChanged() {
        Car car1 = new Car(50);
        collection.remove(car1);
        assertEquals(51, collection.get(50).getId());
        collection.removeAt(10);
        assertEquals(11, collection.get(10).getId());
    }

    @Test 
    public void whenCollectionClearedThenSizeZero() {
        collection.clear();
        assertEquals(0, collection.size());
    }

    @Test
    public void whenSizeCalledThenCorrectSizeReturned() {
        assertEquals(100, collection.size());
    }

    @Test
    public void whenAddMoreThanCapacityThenSizeIncreased() {
        for (int i = 100; i < 150; i++) {
            collection.add(new Car(i));
        }
        assertEquals(150, collection.size());
    }


}
